language: node_js

node_js:
  - 12

sudo: true

addons:
  chrome: stable

branches:
only:
  - master
  - dev2

cache:
  directories:
    - ~/.cache
    - node_modules

stages:
  - name: ci-master
    if: (type != pull_request) AND (branch = master)
  - name: ci-branch
    if: type = (pull_request) OR (type = push)

jobs:
  include:
    - stage: ci-master
      script: echo "master build!"
    - stage: ci-branch
      script: echo "branch build!"
